#!/bin/bash

# .husky/commit-msg

COMMIT_MSG_FILE=$1
COMMIT_MSG=$(cat "$COMMIT_MSG_FILE")

if [[ ! "$COMMIT_MSG" =~ ^(✨|🐛|♻️ |🎨|🔧|📝|🧪)[[:space:]](feat|fix|refactor|style|chore|docs|test)(\(.+\))?:[[:space:]].{1,100}$ ]]; then
	echo "Ошибка: неправильный формат сообщения коммита."
	echo "Используй один из следующих форматов:"
	echo "  ✨ feat: описание"
	echo "  🐛 fix: описание"
	echo "  ♻️ refactor: описание"
	echo "  🎨 style: описание"
	echo "  🔧 chore: описание"
	echo "  📝 docs: описание"
	echo "  🧪 test: описание"
	echo ""
	echo "Можно также указать область:"
	echo "  ✨ feat(auth): добавил авторизацию"
	exit 1
fi

exit 0